export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_ALLOW_ROUTERS = 'SET_ALLOW_ROUTERS'
