export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_SETTINGS = 'SET_SETTINGS'

export const SET_PERMISSION = 'SET_PERMISSION'
